# Use the latest 2.1 version of CircleCI pipeline process engine. 
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Orbs are reusable packages of CircleCI configuration that you may share across projects, enabling you to create encapsulated, parameterized commands, jobs, and executors that can be used across multiple projects.
orbs:
  android: circleci/android@1.0.3

# References are blocks of configurations that we can reference and reuse.
references:

  # Workspaces represent the spaces we work on & are useful for sharing data between jobs.
  # Create a workspace with the ~/code directory.
  workspace: &workspace
               ~/elemento

  # Docker Image Configs
  android_config: &android_config
    working_directory: *workspace
    docker:
      - image: circleci/android:api-29
    environment:
      JVM_OPTS: -Xmx3200m

  gradle_key: &gradle_key
                jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  restore_gradle_cache: &restore_gradle_cache
    restore_cache:
      key: *gradle_key

  save_gradle_cache: &save_gradle_cache
    save_cache:
      paths:
        - ~/.gradle
      key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}

  android_dependencies: &android_dependencies
    run:
      name: Download Android Dependencies
      command: ./gradlew androidDependencies

  run-lint-tests: &run-lint-tests
    run:
      name: Run Lint Tests
      command: ./gradlew lint test

  run-unit-tests: &run-unit-tests
    run:
      name: Run Unit Test
      command: ./gradlew testDevDebugUnitTest

  store-artifacts: &store-artifacts
    store_artifacts:
      path: app/build/reports
      destination: reports

  store-test-results: &store-test-results
    store_test_results: # for display in Test Summary: https://circleci.com/docs/2.0/collect-test-data/
      path: app/build/test-results

  install-fastlane: &install-fastlane
    run:
      name: Install fastlane
      command: bundle update

  deploy-beta-build: &deploy-beta-build
    run:
      name: Deploy build to Playstore beta channel
      command: bundle exec fastlane beta
      no_output_timeout: 60m


jobs:

  ## Run unit tests
  unit-test-branches:
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - *run-unit-tests
      - *run-lint-tests
      - *store-artifacts
      - *store-test-results

  deploy-internal:
    environment:
      FASTLANE_LANE: internal
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
      - *install-fastlane
      - *deploy-beta-build
#      - *install-firebase-plugin
#      - *install-firebase-tools
#      - *deploy-firebase-build

  deploy-prod:
    environment:
      FASTLANE_LANE: prod
    <<: *android_config
    steps:
      - checkout
      - *restore_gradle_cache
      - *android_dependencies
      - *save_gradle_cache
#      - *install-fastlane
#      - *install-firebase-plugin
#      - *install-firebase-tools
      #- *deploy-firebase-build

workflows:
  # Below is the definition of your workflow.
  # Inside the workflow, you provide the jobs you want to run, e.g this workflow runs the build-and-test job above.
  # CircleCI will run this workflow on every commit.
  # For more details on extending your workflow, see the configuration docs: https://circleci.com/docs/2.0/configuration-reference/#workflows
  version: 2
  unit-test-for-feature-branches:
    jobs:
      - unit-test-branches:
          pull_request: true
          filters:
            branches:
              ignore:
                - develop
                - master


  deploy-build-to-beta:
    jobs:
      - deploy-internal:
          filters:
            branches:
              only: develop
      - deploy-prod:
          filters:
            branches:
              only: master


  # Run instrumented tests
#  test_instrumented:
#    environment:
#      TERM: dumb
#      JVM_OPTS: -Xmx3200m
#    docker:
#      - image: circleci/android:api-28
#      - image: google/cloud-sdk:latest
#    steps:
#      - checkout
#      - *restore_gradle_cache
#      - *attach_build_workspace
#      - run:
#          name: Export Key
#          command: ./gradlew exportFirebaseTestlabKey
#      - run:
#          name: Set Google Cloud project
#          command: gcloud config set project agnus-2fff8
#      - run:
#          name: Authenticate with Google Cloud
#          command: gcloud auth activate-service-account firebase-testlab@agnus-2fff8.iam.gserviceaccount.com --key-file app/build/firebase-testlab-key.json
#      - run:
#          name: Run instrumented test on Firebase Test Lab
#          #          command: gcloud firebase test android run .firebase/testlab.yml:instrumented-tests --results-bucket=gs://firebase-testlab-bucket --results-dir=${CIRCLE_WORKFLOW_JOB_ID}
#          command: gcloud firebase test android run .firebase/testlab.yml:instrumented-tests
#      - run:
#          name: Download instrumented test results
#          command: mkdir build/firebase
#          command: gsutil -m cp -r -U "`gsutil ls gs://firebase-testlab-bucket/${CIRCLE_WORKFLOW_JOB_ID}`*" build/firebase
#      - store_test_results
#          path: ...
#      - store_artifacts:
#          path: build/firebase
#          destination: firebase
#commit:
#  jobs:
#    - dependencies:
#        filters:
#          branches:
#            ignore:
#              - master
#    - build_debug:
#        requires:
#          - dependencies
#        filters:
#          branches:
#            ignore:
#              - master
#    - test_unit_debug:
#        requires:
#          - build_debug
#        filters:
#          branches:
#            ignore:
#              - master
#  deploy:
#    jobs:
#      - dependencies:
#          filters:
#            branches:
#              only:
#                - master
#      - build_release:
#          requires:
#            - dependencies
#          filters:
#            branches:
#              only:
#                - master
#      - test_unit_release:
#          requires:
#            - build_release
#          filters:
#            branches:
#              only:
#                - master
#      - deploy:
#          requires:
#            - test_unit_release
#          filters:
#            branches:
#              only:
#                - master